modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/simply-kel/alinlib/issues"
license = "MIT"

[[mods]]
displayTest = "IGNORE_ALL_VERSION"
modId = "alinlib"
version = "${project.version}"
displayURL = "https://modrinth.com/mod/alinlib"
displayName = "AlinLib"
updateJSONURL = "https://api.modrinth.com/updates/alinlib/forge_updates.json"
authors = "Im_Kel (Kel Cuprum)"
credits = "dima_dencep [#1, #4, #5], ImGRUI [Stealth mode algorithm]"
description = "A library to facilitate mod development by Kel Cuprum"
logoFile = "assets/alinlib/icon_forge.png"

[[dependencies.alinlib]]
modId = "forge"
mandatory = true
versionRange = "[47.3.0,]"
ordering = "NONE"
side = "BOTH"

[[dependencies.alinlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"