modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/simply-kel/alinlib/issues"
license="MIT"

[[mods]]
displayTest = "IGNORE_ALL_VERSION"
modId = "alinlibtest"
version = "${version}"
displayURL = "https://modrinth.com/mod/alinlib"
displayName = "AlinLib Demo"
updateJSONURL = "https://api.modrinth.com/updates/alinlib/forge_updates.json"
authors = "Im_Kel (Kel Cuprum)"
credits = "dima_dencep"
description = "A library to facilitate mod development by Kel Cuprum"
logoFile = "assets/alinlibtest/textures/gui/widget/test/well.png"

[[dependencies.alinlibtest]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.alinlibtest]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"